services:
  api:
    build:
      context: ./FinancialAnalytics.API
      dockerfile: Dockerfile
    container_name: financial_api
    environment:
      - ConnectionStrings__DefaultConnection=Server=ec2-18-222-25-254.us-east-2.compute.amazonaws.com;Port=3306;Database=financial_analytics;User=root;Password=Smith3976!;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5245:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financial_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_TARGET=http://api:8080
    depends_on:
      - api
